### ISSUE TITLE
Можно хранить имя сразу в коде и ещё всякое

### ISSUE THREAD

**Issue by ktwzk** [He4eT/BadBarCodeReader#1]
Не знаю, что за йобу ты пишешь, но она интересная :) Можешь игнорировать это ишью, крч

Code 128 умеет хранить не только цифры, но и латинские буквы, поэтому почему бы не хранить имя транслитом сразу на коде? А то введение кучи имён вручную -- это боль же. 
Ну и ещё у тебя  от `log.innerHTML = [${Store[code].visits.length}] ${Store[code].name}<br>+ log.innerHTML`, страница начнёт кушать очень много памяти, но это ладно.

**Comment by ktwzk** [comment]
А вот самый адекватный прайм-чек из всех, что я видел: http://www.javascripter.net/faq/numberisprime.htm

**Comment by He4eT** [comment]
@kotwizkiy Да, всё верно. Это просто набросок йобы, чтобы было что-то перед глазами)

С именами думаем как лучше поступить, пока всё не точно. `log` просто для дебага вставлен.
За прайм-чек спасибо!

Не распространяйся про йобу, пожалуйста, все любят сюрпризы =)

**Comment by ktwzk** [comment]
А, если с именами/номерами там какая-то идея особая, то оки :)

Оф корс, я даже сам не хочу понимать, как оно вообще задумано, исключительно техническая часть заинтересовала.

**Comment by ktwzk** [comment]
(а ещё могу выделить тебе закрытый репо в моём студенческом акке, чтоб не палиться другим)
